### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by zhuwq0** [AI4EPS/ADTomo.jl#2]
1. The current code only uses 1 CPU. How to extend it to use all CPUs on the server? Or is adding MPI an easier solution? Because we need to repeatedly run the Eikonal solver for N sources.
2. The locations of sources and receivers are not on the grid points. So we are thinking to add bilinear interpolation to extract the accurate travel time. Any suggestions how to implement that more efficiently.
3. The current code only calculates the gradients of velocity. We discussed how to calculate the gradient of source location before, but did not get it working. Actually, if we swap the source and receiver location (the traveltime is still the same), the gradient of source location is simply the gradient of traveltime field. What is a good way to calculate (partial t / partial x, partial t / partial y, partial t / partial z)? 
4. Code problems: We are comparing the 2d (Eikonal.h) and 3d (Eikonal3D.cpp) codes. They are not exactly the same. A few places we do not understand:
- [g[this_id] = 0.0](https://github.com/AI4EPS/ADTomo.jl/blob/dcd4c072d39550ea49269cc60c9d60b0adbec7e9/deps/CustomOps/Eikonal3D/Eikonal3D.cpp#L167C26-L167C26) is set in the 3d code. But [rhs = 0](https://github.com/AI4EPS/ADEikonal.jl/blob/dcd4c072d39550ea49269cc60c9d60b0adbec7e9/deps/CustomOps/Eikonal/Eikonal.h#L103C5-L103C29) is set in the 2d code.
- Can not understand what this line is doing: [t = T(t.col(), t.row(), 0.0);](https://github.com/AI4EPS/ADTomo.jl/blob/dcd4c072d39550ea49269cc60c9d60b0adbec7e9/deps/CustomOps/Eikonal3D/Eikonal3D.cpp#L195)
- Can we just use this condition (fabs(u[i] - u0[i])<1e-6) to replace the zero_id? Somehow it will produce segment fault error.

**Comment by xialing2003** [comment]
I have some thoughts about the 4th question.

 [g[this_id] = 0.0](https://github.com/AI4EPS/ADTomo.jl/blob/dcd4c072d39550ea49269cc60c9d60b0adbec7e9/deps/CustomOps/Eikonal3D/Eikonal3D.cpp#L167C26-L167C26) and [rhs = 0](https://github.com/AI4EPS/ADEikonal.jl/blob/dcd4c072d39550ea49269cc60c9d60b0adbec7e9/deps/CustomOps/Eikonal/Eikonal.h#L103C5-L103C29) all mean that at this grid point, partial L / partial f equals zero. This point is where the seismic event happens and the arrival time of this point does not record any information of velocity. The arrival time at this point will not contribute to the loss function so both partial L / partial f and partial L / partial u equal zero at this grid point. 

As we only care about partial L / partial f, we can ignore g and let partial L / partial f equal zero in the end, as it shows in the 2D code. Besides, as it has a check before generating the matrix, other points will not interpret this source point when solving the problem and they will never be interpreted as partial L / partial f of the source point equals zero. In the 3D situation, it first tries to let partial L / partial u equal zero. The purpose of [t = T(t.col(), t.row(), 0.0);](https://github.com/AI4EPS/ADTomo.jl/blob/dcd4c072d39550ea49269cc60c9d60b0adbec7e9/deps/CustomOps/Eikonal3D/Eikonal3D.cpp#L195) is to ensure that the source point will find its partial L / partial f equals zero and other grid points will not be disturbed either. 

I have used (fabs(u[i] - u0[i])<1e-6) to replace the zero_id and I have not found any error.
